# Site settings
title: PrankDNS
description: DNS hijack your friends
domain: prank.domains
# TODO: Figure out how not to need this.
url: "http://prank.domains"

# Build settings
markdown: kramdown
permalink: pretty

# SpinWang
#analytics_tracking_id: UA-10349264-3

analytics_tracking_id: UA-10349264-4
